# Generated by Django 5.2.4 on 2025-07-19 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangrah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='sangrah.streamplatform'),
            preserve_default=False,
        ),
    ]
