# Generated by Django 5.2.4 on 2025-07-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangrah', '0004_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='number_of_rating',
            field=models.IntegerField(default=0),
        ),
    ]
